### ISSUE TITLE
duplicate 'systemConfig' added in TiddlerInFilePlugin

### ISSUE THREAD

**Issue by PengjuYan** [YakovL/TiddlyWiki_DarkModePlugin#1]
I'm using the amazing `TiddlerInFilePlugin` as a helper to facilitate my plugin development.

There's a suspicious minor defect in it. When an external file is taken as a plugin, then the tag `systemConfig` will be appended no matter if one is already there. In some cases my tiddler will end up with duplicated `systemConfig` tags. I made the following modification in my repo, but did not thoroughly test it.

```
if (!tiddler.tags.includes('systemConfig')) {
    tiddler.tags.push('systemConfig');
}
```

**Comment by YakovL** [comment]
Hi @PengjuYan , would you mind moving this issue to the [TIFP repo](https://github.com/YakovL/TiddlyWiki_TiddlerInFilePlugin)? It's quick to fix (should use `pushUnique` instead), but it's easier to track (and reference) things when they are in place.

Also, I'll be glad if you star the plugins you like on Github (like TIFP and DMP). It's not a big deal, but still nice to have social appreciation visualized :)

**Comment by PengjuYan** [comment]
Good. Learned something new: `pushUnique` :-)

**Comment by YakovL** [comment]
Fixed in https://github.com/YakovL/TiddlyWiki_TiddlerInFilePlugin/commit/5eb2ae2ad8b3a1d4caaa12a88e7279197eb12606
